CONTINENTS = {
    "North America":             {"bonus": 5,  "color": "#E8A838"},
    "South America":             {"bonus": 3,  "color": "#44AA44"},
    "Europe":                    {"bonus": 5,  "color": "#4488CC"},
    "Africa":                    {"bonus": 3,  "color": "#CC8844"},
    "Middle East & Central Asia":{"bonus": 3,  "color": "#CC6644"},
    "South & Southeast Asia":    {"bonus": 4,  "color": "#8844CC"},
    "East Asia":                 {"bonus": 4,  "color": "#CC4488"},
    "Russia & North Asia":       {"bonus": 4,  "color": "#887755"},
    "Oceania":                   {"bonus": 2,  "color": "#44AACC"},
}

TERRITORIES = {
    # North America
    "Alaska":            "North America",
    "Western Canada":    "North America",
    "Eastern Canada":    "North America",
    "Quebec":            "North America",
    "Pacific NW":        "North America",
    "Great Plains":      "North America",
    "Eastern USA":       "North America",
    "Southern USA":      "North America",
    "Mexico":            "North America",
    "Central America":   "North America",
    # South America
    "Venezuela":         "South America",
    "Brazil North":      "South America",
    "Brazil South":      "South America",
    "Peru":              "South America",
    "Argentina":         "South America",
    # Europe
    "Iceland":           "Europe",
    "Britain":           "Europe",
    "Scandinavia":       "Europe",
    "W. Europe":         "Europe",
    "C. Europe":         "Europe",
    "S. Europe":         "Europe",
    "E. Europe":         "Europe",
    "Ukraine":           "Europe",
    # Africa
    "N. Africa":         "Africa",
    "W. Africa":         "Africa",
    "C. Africa":         "Africa",
    "E. Africa":         "Africa",
    "S. Africa":         "Africa",
    "Madagascar":        "Africa",
    # Middle East & Central Asia
    "Turkey":            "Middle East & Central Asia",
    "Arabia":            "Middle East & Central Asia",
    "Iran":              "Middle East & Central Asia",
    "C. Asia":           "Middle East & Central Asia",
    "Afghanistan":       "Middle East & Central Asia",
    # South & SE Asia
    "India":             "South & Southeast Asia",
    "Sri Lanka":         "South & Southeast Asia",
    "Indochina":         "South & Southeast Asia",
    "SE Asia":           "South & Southeast Asia",
    "Indonesia":         "South & Southeast Asia",
    "Philippines":       "South & Southeast Asia",
    # East Asia
    "China N":           "East Asia",
    "China S":           "East Asia",
    "Korea":             "East Asia",
    "Japan":             "East Asia",
    "Mongolia":          "East Asia",
    "Taiwan":            "East Asia",
    # Russia
    "W. Russia":         "Russia & North Asia",
    "Siberia W":         "Russia & North Asia",
    "Siberia C":         "Russia & North Asia",
    "Siberia E":         "Russia & North Asia",
    "Kamchatka":         "Russia & North Asia",
    # Oceania
    "W. Australia":      "Oceania",
    "E. Australia":      "Oceania",
    "New Zealand":       "Oceania",
}

ADJACENCY = {
    "Alaska":          ["Western Canada", "Pacific NW", "Kamchatka"],
    "Western Canada":  ["Alaska", "Pacific NW", "Great Plains", "Eastern Canada"],
    "Eastern Canada":  ["Western Canada", "Quebec", "Eastern USA"],
    "Quebec":          ["Eastern Canada", "Eastern USA"],
    "Pacific NW":      ["Alaska", "Western Canada", "Great Plains", "Eastern USA"],
    "Great Plains":    ["Western Canada", "Pacific NW", "Eastern USA", "Southern USA", "Mexico"],
    "Eastern USA":     ["Eastern Canada", "Quebec", "Pacific NW", "Great Plains", "Southern USA"],
    "Southern USA":    ["Great Plains", "Eastern USA", "Mexico"],
    "Mexico":          ["Great Plains", "Southern USA", "Central America"],
    "Central America": ["Mexico", "Venezuela"],

    "Venezuela":       ["Central America", "Brazil North", "Peru"],
    "Brazil North":    ["Venezuela", "Brazil South", "Peru"],
    "Brazil South":    ["Brazil North", "Peru", "Argentina"],
    "Peru":            ["Venezuela", "Brazil North", "Brazil South", "Argentina"],
    "Argentina":       ["Brazil South", "Peru"],

    "Iceland":         ["Britain", "Scandinavia"],
    "Britain":         ["Iceland", "Scandinavia", "W. Europe", "C. Europe"],
    "Scandinavia":     ["Iceland", "Britain", "C. Europe", "E. Europe", "W. Russia"],
    "W. Europe":       ["Britain", "C. Europe", "S. Europe", "N. Africa"],
    "C. Europe":       ["Britain", "Scandinavia", "W. Europe", "S. Europe", "E. Europe"],
    "S. Europe":       ["W. Europe", "C. Europe", "E. Europe", "Turkey", "N. Africa"],
    "E. Europe":       ["Scandinavia", "C. Europe", "S. Europe", "Ukraine"],
    "Ukraine":         ["E. Europe", "W. Russia", "Turkey", "C. Asia", "Iran"],

    "N. Africa":       ["W. Europe", "S. Europe", "W. Africa", "C. Africa", "E. Africa", "Arabia"],
    "W. Africa":       ["N. Africa", "C. Africa"],
    "C. Africa":       ["N. Africa", "W. Africa", "E. Africa", "S. Africa"],
    "E. Africa":       ["N. Africa", "C. Africa", "S. Africa", "Madagascar", "Arabia"],
    "S. Africa":       ["C. Africa", "E. Africa", "Madagascar"],
    "Madagascar":      ["E. Africa", "S. Africa"],

    "Turkey":          ["S. Europe", "Ukraine", "Arabia", "Iran", "N. Africa"],
    "Arabia":          ["Turkey", "Iran", "N. Africa", "E. Africa"],
    "Iran":            ["Turkey", "Arabia", "Ukraine", "C. Asia", "Afghanistan"],
    "C. Asia":         ["Ukraine", "Iran", "Afghanistan", "China N", "Mongolia", "Siberia W"],
    "Afghanistan":     ["Iran", "C. Asia", "India", "China N"],

    "India":           ["Afghanistan", "China S", "Sri Lanka", "SE Asia", "Indochina"],
    "Sri Lanka":       ["India"],
    "Indochina":       ["India", "SE Asia", "Indonesia", "China S", "Korea"],
    "SE Asia":         ["India", "Indochina", "Indonesia", "China S"],
    "Indonesia":       ["SE Asia", "Indochina", "Philippines", "W. Australia"],
    "Philippines":     ["Indonesia", "Taiwan", "Japan"],

    "China N":         ["Afghanistan", "C. Asia", "Mongolia", "Korea", "China S"],
    "China S":         ["India", "China N", "Korea", "SE Asia", "Indochina", "Taiwan"],
    "Korea":           ["China N", "China S", "Indochina", "Japan", "Siberia E"],
    "Japan":           ["Korea", "Philippines", "Taiwan", "Siberia E"],
    "Mongolia":        ["C. Asia", "China N", "Siberia C", "Siberia E"],
    "Taiwan":          ["China S", "Philippines", "Japan"],

    "W. Russia":       ["Scandinavia", "Ukraine", "Siberia W"],
    "Siberia W":       ["W. Russia", "C. Asia", "Siberia C"],
    "Siberia C":       ["Siberia W", "Mongolia", "Siberia E"],
    "Siberia E":       ["Siberia C", "Mongolia", "Korea", "Japan", "Kamchatka"],
    "Kamchatka":       ["Alaska", "Siberia E"],

    "W. Australia":    ["Indonesia", "E. Australia"],
    "E. Australia":    ["W. Australia", "New Zealand"],
    "New Zealand":     ["E. Australia"],
}

ALL_TERRITORIES = list(TERRITORIES.keys())
